version: '3'
services:
   jupyter:
      image: jupyter_redis
      environment:
         - JUPYTER_ENABLE_LAB=yes
         - JUPYTER_TOKEN=bdp2_password
         - CHOWN_HOME=yes
         - CHOWN_HOME_OPTS=-R
      networks:
         - backend
         - frontend
      user: root
      volumes:
         - ~/review/work:/home/jovyan
      ports:
        - 80:8888
   redis:
      image: redis
      command: redis-server
      volumes:
         - ~/review/work:/data
      networks:
         - backend
networks:
  backend:
      driver: bridge
  frontend:
      driver: bridge
