version: '3'
services:
   jupyter:
      image: jupyter_redis
      environment:
         - JUPYTER_ENABLE_LAB=yes
         - JUPYTER_TOKEN="bdp2_password"
         - CHOWN_HOME=yes
         - CHOWN_HOME_OPTS="-R"
      networks:
         - bdp2-net
      user:
           root
      volumes:
         - ~/review/work:/home/jovyan
      ports:
         - 8080:80
   redis:
      image: redis
      command: redis-server
      volumes:
         - ~/review/work:/data
      networks:
         - bdp2-net
networks:
  bdp2-net:
